### ISSUE TITLE
CSS not working.

### ISSUE THREAD

**Issue by collegeimprovements** [jasonseifer/treebook#1]
I cloned treebook to my mac, and then deleted the gem.lock file, run bundle install and then run rake db:migrate but the css and js seems not working. Application is working  fine but doesn't look pretty of nice in appearance. 
Do I have made any mistake ? Is there any workaround ?

**Comment by jonathanamat** [comment]
Having the same problem as well.

**Comment by mansoorkhan1** [comment]
hi any one there? I have some issue
